# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colloquialisms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colloquialism',
            name='allow_auto_tag',
            field=models.BooleanField(default=True),
        ),
    ]
